### ISSUE TITLE
eduSTAR.NET Disco Plugin issue

### ISSUE THREAD

**Issue by timc1045** [garysharp/Disco#100]
Hi Gary,

The eduSTAR.NET plugin is no longer able to generate wireless certificates as of the new DET certificate updates displaying the following error in the logs indicating that Disco may be using an old API?

Task Name: eduSTAR.net - Certificate Retrieval; SessionId: ----; At: 'C:\Disco File Store\Plugins\eduSTARnet\DiscoCommunity.EduSTARnet.dll'; Exception: **InvalidOperationException: Unable to Uncompress (Server returned: An error has occurred, details: This version of the eduSTAR.net Connection Utility has expired. Please download the latest version from the eduSTAR Software Catalogue**); at DiscoCommunity.EduSTARnet.Internal.Interop.CertificateRetrieval.LoadCertificate(Int32 Index, Configuration Configuration) in e:\Disco\Source Repository\Disco-EduSTARnet\Source\Plugin\Internal\Interop\CertificateRetrieval.cs:line 127
 at DiscoCommunity.EduSTARnet.Internal.CertificateRetrievalTask.ExecuteTask() in e:\Disco\Source Repository\Disco-EduSTARnet\Source\Plugin\Internal\CertificateRetrievalTask.cs:line 123
 at Disco.Services.Tasks.ScheduledTask.Execute(IJobExecutionContext context); Inner: FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. ; at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
 at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
 at System.Convert.FromBase64String(String s)
 at DiscoCommunity.EduSTARnet.Internal.Interop.CertificateRetrieval.LoadCertificate(Int32 Index, Configuration Configuration) in e:\Disco\Source Repository\Disco-EduSTARnet\Source\Plugin\Internal\Interop\CertificateRetrieval.cs:line 88

Is there any chance that this could be fixed?

Cheers,
Tim

**Comment by garysharp** [comment]
Hi Tim,

A new version of the eduSTAR.net plugin has been released for Disco ICT v2.2 (currently in Beta). It addresses this issue and adds some new features to assist with certificate/wireless profile migration.

I'll get in touch with you tomorrow with more details on the Beta program.
