### ISSUE TITLE
Bug: Missing dependency for document creation

### ISSUE THREAD

**Issue by timc1045** [garysharp/Disco#101]
Disco version: v2.2.16274.0130 is missing 'zxing' causing the following exception when generating documents from any scope. It does not appear to matter if the document contains a barcode or not.

`Global Application Exception Caught; FileNotFoundException: Could not load file or assembly 'zxing, Version=0.14.0.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60' or one of its dependencies. The system cannot find the file specified.; at Disco.Services.Documents.QRCodeBinaryEncoder.Encode(Byte[] Content, Int32 Width, Int32 Height)
 at Disco.BI.Interop.Pdf.PdfGenerator.GenerateFromTemplate(DocumentTemplate dt, DiscoDataContext Database, IAttachmentTarget Data, User CreatorUser, DateTime TimeStamp, DocumentState State, Boolean FlattenFields)
 at Disco.Web.Areas.API.Controllers.UserController.GeneratePdf(String id, String Domain, String DocumentTemplateId)
 at lambda_method(Closure , ControllerBase , Object[] )
 at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
 at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)`

**Comment by garysharp** [comment]
In Disco ICT 2.2 a new .NET port of the Java ZXing library was used. This library is used to detect and decode QR Codes. In 2.2 the library is also used to *generate* the QR Codes in a compressed binary format (previously iTextSharp was used).

Sadly the old and new library projects used different versioning schemas.
The old library was v1.0.4406.24543 and the new library is v0.14.0.0.
During the initial data-collection phase (File Costing) MSI determined a newer version of the library was already installed (when doing an upgrade). Once the upgrade began committing, the old version of Disco ICT is removed (which also removed the zxing.dll library). As such, the new library was never installed.

This is corrected in dc8a5ab8061722e20da2adc46409c0dfbcf2c493 where the new library has been rebuilt with a new (and more fitting) name (ZXingNet.dll). As this is a new file to the MSI no comparison is done. The old library (zxing.dll) is removed, and the new one (ZXingNet.dll) added.
