### ISSUE TITLE
LWT Warranty Error

### ISSUE THREAD

**Issue by mickyvx** [garysharp/Disco#113]
When using the Warranty tab in a job, the warranty Provider Details fails with the below error.

```
 Error:
The underlying connection was closed: An unexpected error occurred on a receive.

Error Type: WebException
Stack Trace:
at System.Net.HttpWebRequest.GetResponse()
at LWT.DiscoPlugin.Internal.LWTJobDetails.LoadJobDetailsFromWeb(Int32 OnlineWarrantyId, String DeviceSerialNumber) in e:\Disco\Source Repository\Disco-LWTPlugin\LWT.DiscoPlugin\Internal\LWTJobDetails.cs:line 160
at LWT.DiscoPlugin.Internal.LWTJobDetails.LoadJobDetails(DiscoDataContext Database, String Reference, String DeviceSerialNumber) in e:\Disco\Source Repository\Disco-LWTPlugin\LWT.DiscoPlugin\Internal\LWTJobDetails.cs:line 52
at LWT.DiscoPlugin.Features.LWTWarrantyProviderFeature.JobDetailsViewModel(DiscoDataContext Database, Controller controller, Job Job) in e:\Disco\Source Repository\Disco-LWTPlugin\LWT.DiscoPlugin\Features\LWTWarrantyProviderFeature.cs:line 63
at Disco.Web.Controllers.JobController.WarrantyProviderJobDetails(Int32 id)
Inner Exception: The client and server cannot communicate, because they do not possess a common algorithm
Error Type: WebException
Stack Trace:
at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc) at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential) at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint) at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) at System.Net.ConnectStream.WriteHeaders(Boolean async)
```

**Comment by mickyvx** [comment]
Seems to be related to TLS protocols being disabled on the server. I had disabled TLS 1.0 and 1.1 as they are insecure, after enabling these the plugin appears to be working fine. Will need to determine which protocol exactly it does not like being disabled.

**Comment by garysharp** [comment]
TLS 1.2 can be enabled machine-wide for all dotnet applications.
As of the v2.3 release of Disco ICT, TLS 1.2 is explicitly enabled.
