### ISSUE TITLE
Error when unassigning an offline device from user

### ISSUE THREAD

**Issue by Andrew01948** [garysharp/Disco#114]
I am receiving an error when trying to unassign a device from a user. This device was added as an offline device.

See stack trace below:

Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. Refresh ObjectStateManager entries.
[System.Data.Entity.Infrastructure.DbUpdateConcurrencyException]

Stack Trace:
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at Disco.Data.Repository.DiscoDataContext.SaveChanges()
   at Disco.Web.Areas.API.Controllers.DeviceController.UpdateAssignedUserId(Device device, String UserId)
   at Disco.Web.Areas.API.Controllers.DeviceController.Update(String id, String key, String value, Boolean redirect)
   at Disco.Web.Areas.API.Controllers.DeviceController.UpdateAssignedUserId(String id, String AssignedUserId, Boolean redirect)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<>c__DisplayClass2a.<BeginInvokeAction>b__20()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)

Any assistance would be appreciated thank you

This is on a fresh install of the newest version.

**Comment by garysharp** [comment]
Hi @Andrew01948 
This occurs when using SQL 2014 or newer with the public release of DiscoICT. It was fixed some time ago (although not committed to source for a while 4fca015).
If possible, reach out to me via the EduMail GAL to get access to our Slack channel where you can access the latest versions of DiscoICT.

**Comment by garysharp** [comment]
This issue was fixed with the v2.3 release
